version: '3.8'

services:
  # MySQL Database for Development
  mysql:
    image: mysql:8.0
    container_name: greendrive-mysql-fullstack-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: greendrive_db
      MYSQL_USER: greendrive_user
      MYSQL_PASSWORD: greendrive_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_fullstack_dev_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - greendrive-fullstack-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend for Development
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: greendrive-backend-fullstack-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/greendrive_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_PROPERTIES_HIBERATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERATE_FORMAT_SQL: true
      JWT_SECRET: thisIsMysecregtfrdesww233hoaiklasdleasdnamdgkjjhhtdhttebd54ns8877465sbbdd
      JWT_EXPIRATION: 3600000
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - greendrive-fullstack-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Frontend for Development (assuming React/Vite)
  frontend:
    build:
      context: ../GreenDrive-Frontend  # Adjust this path to your frontend folder
      dockerfile: Dockerfile.dev
    container_name: greendrive-frontend-fullstack-dev
    restart: unless-stopped
    ports:
      - "5173:5173"  # Vite dev server port
    environment:
      - VITE_API_URL=http://localhost:8080/api
      - NODE_ENV=development
    volumes:
      - ../GreenDrive-Frontend/src:/app/src  # Adjust path to your frontend source
      - ../GreenDrive-Frontend/public:/app/public
      - ../GreenDrive-Frontend/package.json:/app/package.json
      - ../GreenDrive-Frontend/vite.config.js:/app/vite.config.js
      - /app/node_modules  # Exclude node_modules from volume mount
    depends_on:
      - backend
    networks:
      - greendrive-fullstack-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: greendrive-phpmyadmin-fullstack-dev
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345678
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - greendrive-fullstack-dev-network

volumes:
  mysql_fullstack_dev_data:
    driver: local

networks:
  greendrive-fullstack-dev-network:
    driver: bridge 